---
- name: Check nginx app health and run diagnostics if unavailable
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        urls:
          - https://demo3.sandbox566.opentlc.com/
            # metadata:
            #   target_host: ec2-18-133-188-246.eu-west-2.compute.amazonaws.com # demo-app-nginx
        delay: 30
        status_code: 200
        timeout: 5
        verify_ssl: false
  rules:

    - name: Debug all events
      condition: event.url_check.status is defined
      action:
        debug:
          msg: "node: {{ event.url_check.url.split('://')[1].split('/')[0] }}"

    # - name: Debug event
    #   condition: event.url_check.status == "up"
    #   action:
    #     debug:
    #       msg: "Application is up and working as expected"


    # - name: Run diagnostics if nginx app is down
    #   condition: event.url_check.status == "unavailable"
    #   action:
    #     run_job_template:
    #       name: diagnostics_and_notify_snow
    #       organization: Default
    #       job_args:
    #         extra_vars:
    #           target_host: "{{ event.metadata.target_host }}"