---
- name: Check nginx app health and run diagnostics if unavailable
  hosts: localhost
  match_multiple_rules: true
  sources:
    - ansible.eda.url_check:
        urls:
          - https://demo3.sandbox566.opentlc.com/
            # metadata:
            #   target_host: ec2-18-133-188-246.eu-west-2.compute.amazonaws.com # demo-app-nginx
        delay: 30
        status_code: 200
        timeout: 5
  rules:
    # - name: Remediate selinux issue
    #   condition: event.url_check.status is defined
    #   action:
    #     run_module:
    #       name: ansible.builtin.command
    #       arguments:
    #         cmd: cat /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt

    - name: Debug all events
      condition: event.url_check.status is defined
      action:
        debug:
          msg: "{{ event }}"

    - name: Debug event
      condition: event.url_check.status == "unavailable"
      action:
        debug:
          msg: |
            Event received from get_url source:
            {{ event }}


    # - name: Run diagnostics if nginx app is down
    #   condition: event.url_status == "unavailable"
    #   action:
    #     run_job_template:
    #       name: diagnostics_and_notify_snow
    #       organization: Default
    #       job_args:
    #         extra_vars:
    #           target_host: "{{ event.metadata.target_host }}"