---
- name: Respond to Alert Manager alerts
  hosts: all
  execution_strategy: parallel
  sources:
    - name: Listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.normalize_keys:
  rules:
    - name: test match
      condition: event.payload.status == "firing"
      action:
        debug:
          msg: "Event received TEST: {{ event }}"
