---
- name: Respond to Alert Manager alerts
  hosts: all
  #match_multiple_rules: true
  execution_strategy: parallel
  sources:
    - name: Listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.normalize_keys:
  rules:
    - name: Raise incident on SNOW
      condition: >
        event.payload.status == "firing" and
        event.payload.commonLabels.alertname == "selinux status"
      action:
        run_job_template:
          name: snow_raise_incident
          organization: Default
          post_event: true
          job_args:
            job_tags: create_incident
            extra_vars:
              short_description: "{{ event.payload.commonAnnotations.summary }}"
              description: "{{ event.payload.commonAnnotations.description }}"
              instance: "{{ event.payload.commonLabels.instance.split(':')[0] }}"
              severity: "{{ event.payload.commonLabels.severity }}"
              original_event: "{{ event }}"

    - name: Remediate selinux issue
      condition: event.incident_details is defined
      action:
        debug:
          msg: "{{ event }}"

    # - name: Remediate selinux issue
    #   condition: >
    #     event.payload.status == "firing" and
    #     event.payload.commonLabels.alertname == "selinux status"
    #   action:
    #     run_job_template:
    #       name: remediate_selinux
    #       organization: Default

    # - name: Log SELinux resolution
    #   condition: >
    #     event.payload.status == "resolved" and
    #     event.payload.commonLabels.alertname == "selinux status"
    #   action:
    #     debug:
    #       msg: "The selinux issue has been resolved on {{ event.payload.commonLabels.instance.split(':')[0] }}"
