---
- name: Monitor selinux alerts with service now integration
  hosts: all
  execution_strategy: parallel
  sources:
    - name: Listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.normalize_keys:
  rules:
    # Skip remediation for sandbox hosts
    - name: Skip remediation for sandbox hosts
      condition: >
        event.payload.commonLabels.alertname == "selinux not enforcing" and
        event.payload.commonLabels.environment == "sandbox"
      action:
        debug:
          msg: "Host {{ event.payload.commonLabels.instance }} is part of the sandbox environment. Skipping remediation."

    ######################################################################################################################
    # Auto-remediate non-production systems

    - name: Auto-remediate non-production systems for selinux issue and report to Service Now # Audit trail in SNOW
      condition: >
        event.payload.commonLabels.alertname == "selinux not enforcing" and
        not event.payload.commonLabels.environment == "prod"
      action:
        run_workflow_template:
          name: servicenow_auto_remediate_selinux_workflow
          organization: Default
          job_args:
            extra_vars:
              target_host: "{{ event.payload.commonLabels.instance }}"
              short_description: "{{ event.payload.commonAnnotations.summary }}"
              description: "{{ event.payload.commonAnnotations.description }}"
              instance: "{{ event.payload.commonLabels.instance }}"
              severity: "{{ event.payload.commonLabels.severity }}"
              alert_fingerprint: "{{ event.payload.alerts[0].fingerprint }}"

    ######################################################################################################################
    # Raise critical incident if host is tagged as production

    - name: Raise critical incident if host is tagged as production
      condition: >
        event.payload.commonLabels.alertname == "selinux not enforcing" and
        event.payload.commonLabels.environment == "prod"
      action:
        run_workflow_template:
          name: servicenow_full_flow
          organization: Default
          job_args:
            extra_vars:
              target_host: "{{ event.payload.commonLabels.instance }}"
              short_description: "{{ event.payload.commonAnnotations.summary }}"
              description: "{{ event.payload.commonAnnotations.description }}"
              instance: "{{ event.payload.commonLabels.instance }}"
              severity: "critical"
              alert_fingerprint: "{{ event.payload.alerts[0].fingerprint }}"