---
- name: Monitor selinux alerts
  hosts: all
  #match_multiple_rules: true
  execution_strategy: parallel
  sources:
    - name: Listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.normalize_keys:
  rules:

    # Resolve the selinux issue by running the remediate_selinux job template when conditions match
    - name: Remediate selinux issue
      condition: >
        event.payload.status == "firing" and
        event.payload.commonLabels.alertname == "selinux not enforcing"
      action:
        run_job_template:
          name: remediate_selinux
          organization: Default
          job_args:
            extra_vars:
              target_host: "{{ event.payload.commonLabels.instance }}"

    # Log a simple msg when alert manager fires the resolved webhook
    - name: Log SELinux resolution
      condition: >
        event.payload.status == "resolved" and
        event.payload.commonLabels.alertname == "selinux not enforcing"
      action:
        debug:
          msg: "The selinux issue has been resolved on {{ event.payload.commonLabels.instance }}"
