---
- name: Respond to Alert Manager alerts
  hosts: all
  execution_strategy: parallel
  sources:
    - name: Listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.normalize_keys:
  rules:
    - name: Remediate_selinux issue
      condition: >
        event.payload.status == "firing" and
        event.payload.commonLabels.alertname == "selinux status"
      action:
        run_playbook:
          name: remediate_selinux

    - name: Log SELinux resolution
      condition: >
        event.payload.status == "resolved" and
        event.payload.commonLabels.alertname == "selinux status"
      action:
        debug:
          msg: "The selinux issue has been resolved"
