---
- name: Respond to Alert Manager alerts
  hosts: all
  execution_strategy: parallel
  sources:
    - name: Listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: alertmanager selinux alert
      condition: event.payload.status == "firing" and event.payload.commonLabels.alertname == "selinux status"
      action:
        debug:
          var: event



