groups:
- name: eda-demo
  rules:

  # alert if selinux is disabled
  - alert: selinux status
    expr: node_selinux_current_mode == 0
    labels:
      severity: warning
      alertname: selinux status
    annotations:
      summary: "Selinux is disabled on {{ $labels.instance | split \":\" | first }}"
      description: "Selinux has been set to permissive on {{ $labels.instance | split \":\" | first }}"

  - alert: systemd failed service
    expr: node_systemd_unit_state{state="failed"} == 1
    labels:
      severity: warning
      alertname: systemd failed service
    annotations:
      summary: "Host systemd service failed (instance {{ $labels.instance }})"
      description: "systemd service failed\n  VALUE = {{ $value }}"

