---

- name: Install node exporter on application server
  hosts: prometheus-am
  become: true
  vars_files:
    - ../vault.yml
  vars:
    eda_webhook_url: https://aap.sandbox566.opentlc.com/eda-event-streams/api/eda/v1/external_event_stream/86396dd7-a9ef-4008-989a-bb146dfae85b/post/
  roles:
    - prometheus
    - alertmanager
