---

- name: Install node exporter on application server
  hosts: prometheus-am
  become: true
  vars_files:
    - ../vault.yml
  vars:
    eda_webhook_url: https://aap.sandbox566.opentlc.com/eda-event-streams/api/eda/v1/external_event_stream/88e7fc59-f347-401d-bb82-d6275e59a764/post/
  roles:
    - prometheus
    - alertmanager
