---
- name: Run diagnostics on NGINX server
  hosts: demo3.sandbox566.opentlc.com
  become: true
  gather_facts: false

  tasks:

    - name: Check if nginx service is active
      ansible.builtin.service_facts:

    - name: Set nginx service active fact
      set_fact:
        nginx_service_active: "{{ services['nginx'].state == 'running' }}"
      when: services['nginx'] is defined
      failed_when: false
      ignore_errors: true
      vars:
        services: "{{ ansible_facts.services }}"
      register: nginx_service_check

    - name: Fallback nginx service fact if undefined
      set_fact:
        nginx_service_active: false
        nginx_service_error: "Unable to determine nginx service status"
      when: nginx_service_check is failed

    - name: Run nginx config test
      ansible.builtin.command: nginx -t
      register: nginx_config_check
      changed_when: false
      failed_when: false

    - name: Set nginx config facts
      set_fact:
        nginx_config_ok: "{{ nginx_config_check.rc == 0 }}"
        nginx_config_error: >-
          {% if nginx_config_check.rc != 0 %}
          {{ nginx_config_check.stderr }}
          {% else %}
          ""
          {% endif %}

    - name: Get firewalld info
      ansible.posix.firewalld_info:
      register: fw_info
      ignore_errors: true
      failed_when: false

    - name: Check if firewalld is active and port 443 is open
      set_fact:
        firewall_active: "{{ fw_info.firewalld_running | default(false) }}"
        firewall_port_443_open: >-
          {{ '443/tcp' in (fw_info.firewalld.ports | default([])) }}
        firewall_error: >-
          {% if fw_info is failed %}
          Failed to get firewalld info.
          {% else %}
          ""
          {% endif %}

    - name: Set structured diagnostics report
      ansible.builtin.set_stats:
        data:
          diagnostics:
            nginx_service_active: "{{ nginx_service_active | default(false) }}"
            nginx_service_error: "{{ nginx_service_error | default('') }}"
            nginx_config_ok: "{{ nginx_config_ok | default(false) }}"
            nginx_config_error: "{{ nginx_config_error | default('') }}"
            firewall_active: "{{ firewall_active | default(false) }}"
            firewall_error: "{{ firewall_error | default('') }}"
            firewall_port_443_open: "{{ firewall_port_443_open | default(false) }}"
        per_host: false
        aggregate: true
