---
- name: Run diagnostics on nginx app host
  hosts: demo3.sandbox566.opentlc.com
  become: true
  gather_facts: false

  tasks:

    - name: Check if nginx is active
      ansible.builtin.systemd:
        name: nginx
      register: nginx_status
      failed_when: false

    - name: Check nginx configuration syntax
      ansible.builtin.command:
        cmd: nginx -t
      register: nginx_config_test
      ignore_errors: true

    - name: Check if firewalld is running
      ansible.builtin.systemd:
        name: firewalld
      register: firewalld_status
      failed_when: false

    - name: Get list of open ports in firewalld
      ansible.posix.firewalld_info:
      register: firewall_ports
      when: firewalld_status.status == "running"
      failed_when: false

    - name: Set final diagnostic report
      ansible.builtin.set_stats:
        data:
          diagnostics:
            nginx_service_active: "{{ nginx_status.status == 'running' }}"
            nginx_service_error: >-
              {{ nginx_status | default({}) | dict2items | selectattr('key', 'search', 'stderr') | map(attribute='value') | join('\n') | default('') }}
            nginx_config_ok: "{{ nginx_config_test.rc == 0 }}"
            nginx_config_error: "{{ nginx_config_test.stderr | default('') }}"
            firewall_active: "{{ firewalld_status.status == 'running' }}"
            firewall_error: "{{ firewalld_status | to_nice_json }}"
            firewall_port_443_open: >-
              {{ '443/tcp' in (firewall_ports.firewalld_info.ports | default([])) }}
        per_host: false
        aggregate: true
