---
- name: Run diagnostics on nginx server
  hosts: demo3.sandbox566.opentlc.com
  gather_facts: false
  tasks:

    - name: Check if nginx service is active
      ansible.builtin.systemd:
        name: nginx
      register: nginx_service

    - name: Check nginx configuration syntax
      ansible.builtin.command:
        cmd: nginx -t
      register: nginx_config_check
      ignore_errors: true

    - name: Get firewalld status
      community.general.firewalld_info:
      register: firewall_info

    - name: Set simple diagnostic stats
      ansible.builtin.set_stats:
        data:
          diagnostics:
            nginx_service_active: "{{ nginx_service.status.ActiveState == 'active' }}"
            nginx_config_ok: "{{ nginx_config_check.rc == 0 }}"
            nginx_config_error: "{{ nginx_config_check.stderr if nginx_config_check.rc != 0 else '' }}"
            firewall_active: "{{ firewall_info.firewalld_info.active }}"
            firewall_port_443_open: "{{ '443/tcp' in firewall_info.firewalld_info.ports }}"
        aggregate: true
