---
- name: Run diagnostics on nginx host
  hosts: demo3.sandbox566.opentlc.com
  gather_facts: false
  become: true
  tasks:

    - name: Check nginx service status
      ansible.builtin.systemd:
        name: nginx
      register: nginx_status
      failed_when: false

    - name: Test nginx config
      ansible.builtin.command: nginx -t
      register: nginx_config
      failed_when: false

    - name: Check firewalld status
      ansible.builtin.systemd:
        name: firewalld
      register: firewall_status
      failed_when: false

    - name: Get list of open firewall ports
      ansible.builtin.command: firewall-cmd --list-ports
      register: firewall_ports
      failed_when: false

    - name: Generate human-readable diagnostics report
      ansible.builtin.set_fact:
        diagnostics_report: |
          NGINX service active: {{ nginx_status.status.ActiveState == 'active' }}
          NGINX service error: >-
            {% if nginx_status.status.ActiveState != 'active' %}
              {{ nginx_status.status }}
            {% else %}
              N/A
            {% endif %}
          NGINX config test ok: {{ nginx_config.rc == 0 }}
          NGINX config error: >-
            {% if nginx_config.rc != 0 %}
              {{ nginx_config.stderr }}
            {% else %}
              N/A
            {% endif %}
          Firewalld active: {{ firewall_status.status.ActiveState == 'active' }}
          Port 443 open: {{ firewall_ports.stdout_lines | select('match', '^443/tcp') | list | length > 0 }}
          Overall health: >-
            {% if (nginx_status.status.ActiveState == 'active')
                  and (nginx_config.rc == 0)
                  and (firewall_status.status.ActiveState == 'active')
                  and (firewall_ports.stdout_lines | select('match', '^443/tcp') | list | length > 0) %}
              ok
            {% else %}
              issues_detected
            {% endif %}

    - name: Encode diagnostics report as base64
      ansible.builtin.set_fact:
        diagnostics_report_b64: "{{ diagnostics_report | b64encode }}"

    - name: Set structured and raw report as stats
      ansible.builtin.set_stats:
        data:
          diagnostics:
            nginx_service_active: "{{ nginx_status.status.ActiveState == 'active' }}"
            nginx_service_error: >-
              {% if nginx_status.status.ActiveState != 'active' %}
                {{ nginx_status.status }}
              {% else %}
                ''
              {% endif %}
            nginx_config_ok: "{{ nginx_config.rc == 0 }}"
            nginx_config_error: >-
              {% if nginx_config.rc != 0 %}
                {{ nginx_config.stderr }}
              {% else %}
                ''
              {% endif %}
            firewall_active: "{{ firewall_status.status.ActiveState == 'active' }}"
            firewall_port_443_open: "{{ firewall_ports.stdout_lines | select('match', '^443/tcp') | list | length > 0 }}"
            overall_health: >-
              {% if (nginx_status.status.ActiveState == 'active')
                    and (nginx_config.rc == 0)
                    and (firewall_status.status.ActiveState == 'active')
                    and (firewall_ports.stdout_lines | select('match', '^443/tcp') | list | length > 0) %}
                ok
              {% else %}
                issues_detected
              {% endif %}
          diagnostics_report_b64: "{{ diagnostics_report_b64 }}"
        aggregate: true
        per_host: false
