---
- name: Run diagnostics on nginx host
  hosts: demo3.sandbox566.opentlc.com
  gather_facts: false
  become: true
  tasks:

    - name: Check nginx service status
      ansible.builtin.systemd:
        name: nginx
      register: nginx_status
      failed_when: false

    - name: Test nginx config
      ansible.builtin.command: nginx -t
      register: nginx_config
      failed_when: false

    - name: Check firewalld status
      ansible.builtin.systemd:
        name: firewalld
      register: firewall_status
      failed_when: false

    - name: Get list of open firewall ports
      ansible.builtin.command: firewall-cmd --list-ports
      register: firewall_ports
      failed_when: false

    - name: Determine values for diagnostics
      ansible.builtin.set_fact:
        nginx_ok: "{{ nginx_status.status.ActiveState == 'active' }}"
        nginx_error: >-
          {{ '' if nginx_status.status.ActiveState == 'active' else nginx_status.status }}
        config_ok: "{{ nginx_config.rc == 0 }}"
        config_error: >-
          {{ '' if nginx_config.rc == 0 else nginx_config.stderr }}
        fw_active: "{{ firewall_status.status.ActiveState == 'active' }}"
        port_443_open: "{{ '443/tcp' in (firewall_ports.stdout | default('')) }}"
        overall_health: >-
          {% if nginx_status.status.ActiveState == 'active'
                and nginx_config.rc == 0
                and firewall_status.status.ActiveState == 'active'
                and '443/tcp' in (firewall_ports.stdout | default('')) %}
            ok
          {% else %}
            issues_detected
          {% endif %}

    - name: Build human-readable diagnostics report
      ansible.builtin.set_fact:
        diagnostics_report: |
          NGINX service active: {{ nginx_ok }}
          NGINX service error: {{ nginx_error }}
          NGINX config test ok: {{ config_ok }}
          NGINX config error: {{ config_error }}
          Firewalld active: {{ fw_active }}
          Port 443 open: {{ port_443_open }}
          Overall health: {{ overall_health }}

    - name: Encode diagnostics report as base64
      ansible.builtin.set_fact:
        diagnostics_report_b64: "{{ diagnostics_report | b64encode }}"

    - name: Set structured and raw report as stats
      ansible.builtin.set_stats:
        data:
          diagnostics:
            nginx_service_active: "{{ nginx_ok }}"
            nginx_service_error: "{{ nginx_error }}"
            nginx_config_ok: "{{ config_ok }}"
            nginx_config_error: "{{ config_error }}"
            firewall_active: "{{ fw_active }}"
            firewall_port_443_open: "{{ port_443_open }}"
            overall_health: "{{ overall_health | string }}"
          diagnostics_report_b64: "{{ diagnostics_report_b64 }}"
        aggregate: true
        per_host: false
