---
- name: Manage Service Now incidents
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create a ServiceNow incident
      servicenow.itsm.incident:
        state: new
        caller: "eda_user"
        short_description: "{{ short_description }}"
        description: "{{ description }}"
        impact: low
        urgency: low
      register: snow_result
      tags: "create_incident"

    - name: Update work notes on incident
      servicenow.itsm.incident:
        sys_id: "{{ snow_result.record.sys_id }}"
        state: 2 # In Progress
        other:
          work_notes: "Attempting remediation with Event Driven Ansible"
      tags: "update_incident"
      register: incident

    - debug:
        var: incident

    - name: Consolidate all facts and original event into set_stats
      ansible.builtin.set_stats:
        data:
          incident_details: "{{ incident }}"
          original_event: "{{ original_event | default({}) }}"

