---
- name: Remediate SELinux mode
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create a ServiceNow incident
      servicenow.itsm.incident:
        state: new
        caller: "eda_user"
        short_description: "This is an EDA test"
        description: "EDA is on this"
        attachments:
          - path: path/to/attachment.txt
        impact: low
        urgency: low
      register: snow_result