---
- name: TEST
  hosts: ec2-18-171-226-11.eu-west-2.compute.amazonaws.com
  gather_facts: false
  tasks:
    - name: Fetch sosreport
      ansible.builtin.fetch:
        src: /tmp/sos-test.txt
        dest: "/tmp/"
        flat: yes

- name: Upload sosreport to ServiceNow
  hosts: localhost
  gather_facts: false
  tasks:
    # Attach sos report if one has been generated
    - name: Upload sos report to ServiceNow incident
      servicenow.itsm.incident:
        #sys_id: "{{ incident_sys_id }}"
        sys_id: 98370b7cc3c1a6108f8b12d4e40131d0
        attachments:
          - name: sos_report
            #path: "{{ sos_file.files[0].path }}"
            path: /tmp/sos-test.txt
      #when: incident_sys_id is defined
